# Generated by Django 5.1 on 2025-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username_user_phone_user_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
