# Generated by Django 5.1 on 2025-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailverificationcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
