# Generated by Django 5.1 on 2024-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('waitlist_open', 'waitlist open'), ('closed', 'closed')], max_length=20, null=True),
        ),
    ]
