# Generated by Django 5.1 on 2025-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_subscription_created_at_subscription_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('waitlist_open', 'waitlist_open'), ('closed', 'closed')], max_length=20, null=True),
        ),
    ]
