# Generated by Django 5.1.15 on 2026-01-11 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_subscription_last_status'),
        ('courses', '0006_remove_section__time_bitmap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('waitlist_open', 'Waitlist Open'), ('closed', 'Closed')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='unique_user_section'),
        ),
    ]
