services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web
    env_file:
      - .env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    command: sh -c "/app/entrypoint.sh"