# Generated by Django 5.1 on 2024-09-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('subject', models.CharField(max_length=128)),
                ('subject_description', models.CharField(max_length=128)),
                ('subject_course', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=128)),
                ('course_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=6)),
                ('term_desc', models.CharField(max_length=128)),
                ('course_reference_number', models.CharField(max_length=128)),
                ('part_of_term', models.CharField(max_length=128)),
                ('sequence_number', models.CharField(max_length=128)),
                ('campus_description', models.CharField(max_length=128)),
                ('schedule_type_description', models.CharField(max_length=128)),
                ('credit_hours', models.IntegerField(null=True)),
                ('credit_hour_high', models.IntegerField(null=True)),
                ('credit_hour_low', models.IntegerField(null=True)),
                ('credit_hour_indicator', models.CharField(max_length=128, null=True)),
                ('link_identifier', models.CharField(max_length=128, null=True)),
                ('is_section_linked', models.BooleanField()),
                ('faculty', models.JSONField()),
                ('meetings_faculty', models.JSONField()),
                ('is_primary_section', models.BooleanField()),
                ('_time_bitmap', models.CharField(editable=False, max_length=512)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
