# Generated by Django 5.1 on 2024-10-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('term_desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='term_desc',
        ),
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.term'),
        ),
    ]
