# Generated by Django 5.1 on 2024-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_primary_section',
            field=models.BooleanField(default=False),
        ),
    ]
