# Generated by Django 5.1 on 2024-10-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_term_remove_section_term_desc_alter_section_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
