# Generated by Django 5.1 on 2024-10-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_term_registration_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_title', 'subject_course']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['course__subject_course', 'schedule_type_description', 'course_reference_number']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['term']},
        ),
    ]
