# Generated by Django 5.1 on 2025-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_time_bitmap',
            field=models.CharField(editable=False, max_length=512, null=True),
        ),
    ]
