# Generated by Django 5.1 on 2025-07-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_section__time_bitmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='_time_bitmap',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_primary_section',
        ),
    ]
